// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zyvgdptebvkxmihgiszr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dmdkcHRlYnZreG1paGdpc3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjAyMzUsImV4cCI6MjA3MDMzNjIzNX0.OvBX59jBg9_QjlLOfjPNQ-V80NKl-Td6DFYyBhw3U70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});